name: flutter_web_bloc
description: Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
version: 0.21.0
author: Felix Angelov <felangelov@gmail.com>
repository: https://github.com/felangel/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://felangel.github.io/bloc

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter_web: any
  bloc: ^0.15.0
  provider: any

dev_dependencies:
  flutter_web_test: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web
