name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0

dev_dependencies:
  very_good_analysis: ^3.0.1
