name: flutter_dynamic_form
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../../packages/bloc
  bloc_concurrency:
    path: ../../packages/bloc_concurrency
  flutter_bloc:
    path: ../../packages/flutter_bloc
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0

dependency_overrides:
  bloc:
    path: ../../packages/bloc
  flutter_bloc:
    path: ../../packages/flutter_bloc
  bloc_test:
    path: ../../packages/bloc_test

flutter:
  uses-material-design: true
