name: flutter_dynamic_form
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../packages/flutter_bloc
  meta: ^1.1.8

flutter:
  uses-material-design: true
