name: bloc_provider_performance_tests
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:  
  flutter_bloc:
    path: ../../../packages/flutter_bloc
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ">=1.3.0 <2.0.0"

flutter:
  uses-material-design: true
