name: flutter_graphql_jobs
description: A example of how to use a GraphQL client with bloc.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  graphql: ^5.1.3
  json_annotation: ^4.4.0
  meta: ^1.8.0

dependency_overrides:
  bloc:
    path: ../../packages/bloc
  flutter_bloc:
    path: ../../packages/flutter_bloc

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
