#!/bin/bash
(cd ../packages/angular_bloc && flutter clean)
(cd ../packages/bloc && flutter clean)
(cd ../packages/bloc_concurrency && flutter clean)
(cd ../packages/bloc_test && flutter clean)
(cd ../packages/bloc_tools && flutter clean)
(cd ../packages/flutter_bloc && flutter clean)
(cd ../packages/hydrated_bloc && flutter clean)
(cd ../packages/replay_bloc && flutter clean)
echo "All package cleaned"

(cd ../packages/angular_bloc && flutter pub get)
(cd ../packages/bloc && flutter pub get)
(cd ../packages/bloc_concurrency && flutter pub get)
(cd ../packages/bloc_test && flutter pub get)
(cd ../packages/bloc_tools && flutter pub get)
(cd ../packages/flutter_bloc && flutter pub get)
(cd ../packages/hydrated_bloc && flutter pub get)
(cd ../packages/replay_bloc && flutter pub get)
echo "All package dependencies installed"

(cd ../examples/angular_counter && flutter clean)
(cd ../examples/flutter_bloc_with_stream && flutter clean)
(cd ../examples/flutter_complex_list && flutter clean)
(cd ../examples/flutter_counter && flutter clean)
(cd ../examples/flutter_dynamic_form && flutter clean)
(cd ../examples/flutter_firebase_login && flutter clean)
(cd ../examples/flutter_form_validation && flutter clean)
(cd ../examples/flutter_graphql_jobs && flutter clean)
(cd ../examples/flutter_infinite_list && flutter clean)
(cd ../examples/flutter_login && flutter clean)
(cd ../examples/flutter_shopping_cart && flutter clean)
(cd ../examples/flutter_timer && flutter clean)
(cd ../examples/flutter_todos && flutter clean)
(cd ../examples/flutter_weather && flutter clean)
(cd ../examples/flutter_wizard && flutter clean)
(cd ../examples/github_search/angular_github_search && flutter clean)
(cd ../examples/github_search/common_github_search && flutter clean)
(cd ../examples/github_search/flutter_github_search && flutter clean)

echo "All example cleaned"

(cd ../examples/angular_counter && flutter pub get)
(cd ../examples/flutter_bloc_with_stream && flutter pub get)
(cd ../examples/flutter_complex_list && flutter pub get)
(cd ../examples/flutter_counter && flutter pub get)
(cd ../examples/flutter_dynamic_form && flutter pub get)
(cd ../examples/flutter_firebase_login && flutter pub get)
(cd ../examples/flutter_form_validation && flutter pub get)
(cd ../examples/flutter_graphql_jobs && flutter pub get)
(cd ../examples/flutter_infinite_list && flutter pub get)
(cd ../examples/flutter_login && flutter pub get)
(cd ../examples/flutter_shopping_cart && flutter pub get)
(cd ../examples/flutter_timer && flutter pub get)
(cd ../examples/flutter_todos && flutter pub get)
(cd ../examples/flutter_weather && flutter pub get)
(cd ../examples/flutter_wizard && flutter pub get)
(cd ../examples/github_search/angular_github_search && flutter pub get)
(cd ../examples/github_search/common_github_search && flutter pub get)
(cd ../examples/github_search/flutter_github_search && flutter pub get)
echo "All example dependencies installed 🚀 🚀 🚀 "
exit 0
