name: todos_repository

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.7
  rxdart: ^0.22.0
  equatable: ^0.6.0
  firebase_core: ^0.4.0+7
