name: flutter_bloc_with_stream
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency:
    path: ../../packages/bloc_concurrency
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../packages/flutter_bloc

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

dependency_overrides:
  bloc:
    path: ../../packages/bloc
  bloc_test:
    path: ../../packages/bloc_test
  flutter_bloc:
    path: ../../packages/flutter_bloc

flutter:
  uses-material-design: true
