name: flutter_bloc_with_stream
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
