name: shopping_repository
description: A repository that handles shopping-related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
