name: example
description: A new AngularDart project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  angular: ^7.0.0
  angular_bloc:
    path: ../

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0

dependency_overrides:
  bloc:
    path: ../../bloc
  angular_bloc:
    path: ../
