include:
  - package:bloc_lint/recommended.yaml
  - ../../../analysis_options.yaml

analyzer:
  exclude: [build/**]
  errors:
    uri_has_not_been_generated: ignore

linter:
  rules:
    public_member_api_docs: false
