name: angular_dart_examples

on:
  push:
    paths:
      - ".github/workflows/angular_dart_examples.yaml"
      - "packages/angular_bloc/**"
      - "examples/angular_counter/**"
      - "examples/github_search/common_github_search/**"
      - "examples/github_search/angular_github_search/**"

  pull_request:
    paths:
      - ".github/workflows/angular_dart_examples.yaml"
      - "packages/angular_bloc/**"
      - "examples/angular_counter/**"
      - "examples/github_search/common_github_search/**"
      - "examples/github_search/angular_github_search/**"

jobs:
  examples:
    strategy:
      matrix:
        folder:
          [
            "examples/angular_counter",
            "examples/github_search/common_github_search",
            "examples/github_search/angular_github_search",
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        working-directory: ${{ matrix.folder }}
        run: dart pub get

      - name: Install webdev
        if: matrix.folder == 'examples/github_search/angular_github_search'
        working-directory: ${{ matrix.folder }}
        run: |
          dart pub global activate webdev
          webdev build

      - name: Format
        working-directory: ${{ matrix.folder }}
        run: dart format --set-exit-if-changed .

      - name: Analyze
        working-directory: ${{ matrix.folder }}
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        working-directory: ${{ matrix.folder }}
        run: |
          if [ -d "test" ]; then
            dart run build_runner test --fail-on-severe
          fi

  build:
    needs: [examples]
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
