name: angular_dart_examples

on:
  push:
    paths:
      - ".github/workflows/angular_dart_examples.yaml"
      - "packages/angular_bloc/**"
      - "examples/angular_counter/**"
      - "examples/github_search/common_github_search/**"
      - "examples/github_search/angular_github_search/**"

  pull_request:
    paths:
      - ".github/workflows/angular_dart_examples.yaml"
      - "packages/angular_bloc/**"
      - "examples/angular_counter/**"
      - "examples/github_search/common_github_search/**"
      - "examples/github_search/angular_github_search/**"

jobs:
  examples:
    strategy:
      matrix:
        folder:
          [
            "examples/angular_counter",
            "examples/github_search/common_github_search",
            "examples/github_search/angular_github_search",
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - name: Install Dependencies
        working-directory: ${{ matrix.folder }}
        run: flutter pub get
      - name: Format
        working-directory: ${{ matrix.folder }}
        run: flutter format --dry-run --set-exit-if-changed .
      - name: Analyze
        working-directory: ${{ matrix.folder }}
        run: flutter analyze .
      - name: Run tests
        working-directory: ${{ matrix.folder }}
        run: |
          if [ -d "test" ]; then
            flutter pub run build_runner test --fail-on-severe
          fi
  build:
    needs: [examples]
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
