name: bloc_concurrency

on:
  push:
    paths:
      - "packages/bloc_concurrency/**"
      - ".github/workflows/bloc_concurrency.yaml"

  pull_request:
    paths:
      - "packages/bloc_concurrency/**"
      - ".github/workflows/bloc_concurrency.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/bloc_concurrency

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: |
          dart pub global activate coverage 1.2.0
          dart test --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: packages/bloc_concurrency/coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pana:
    defaults:
      run:
        working-directory: packages/bloc_concurrency

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana

      - name: Verify Pub Score
        run: ../../tool/verify_pub_score.sh
