name: bloc_tools

on:
  pull_request:
    paths:
      - ".github/workflows/bloc_tools.yaml"
      - "packages/bloc_tools/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/bloc_tools.yaml"
      - "packages/bloc_tools/**"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/bloc_tools

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze .

      - name: Verify Build
        run: flutter pub run test --run-skipped -t pull-request-only

      - name: Run Tests
        run: flutter test -x pull-request-only --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: packages/bloc_tools/coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pana:
    defaults:
      run:
        working-directory: packages/bloc_tools

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana

      - name: Verify Pub Score
        run: ../../tool/verify_pub_score.sh
