name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'

  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  pana:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
