name: ci

on:
  pull_request:
    paths:
      - "!packages/**"
      - "!.github/workflows/**"
      - "!examples/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
