name: examples

on:
  push:
    paths:
    - 'examples/**'
    - 'packages/**'
    - '!packages/*/example/**'
  pull_request:
    paths:
    - 'examples/**'
    - 'packages/**'
    - '!packages/*/example/**'

env:
  flutter_channel: 'stable'
  flutter_version: '1.12.13+hotfix.7'

jobs:
  # Analyze, test and build an APK for each flutter example.
  analyze-and-test-and-build-apk:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        flutter_folder: ['examples/flutter_bloc_with_stream', 'examples/flutter_complex_list', 'examples/flutter_dynamic_form', 'examples/flutter_firebase_login', 'examples/flutter_firestore_todos', 'examples/flutter_form_validation', 'examples/flutter_infinite_list', 'examples/flutter_login', 'examples/flutter_shopping_cart', 'examples/flutter_timer', 'examples/flutter_todos', 'examples/flutter_weather', 'examples/github_search/flutter_github_search', 'packages/flutter_bloc/example', 'performance_tests/flutter_bloc/bloc_builder', 'performance_tests/flutter_bloc/bloc_provider']
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.OS }}-flutter-cache-${{ env.flutter_version }}
          restore-keys: |
            ${{ runner.OS }}-flutter-cache-

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Analyze and test
        env:
          FLUTTER_DART_HOME: ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin
        run: |
          export PATH=$PATH:$FLUTTER_DART_HOME
          ./scripts/ci.sh ${{ matrix.flutter_folder }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ matrix.package }}.lcov

      - name: Build an APK
        env:
          FLUTTER_DART_HOME: ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin
        run: |
          export PATH=$PATH:$FLUTTER_DART_HOME
          ./scripts/ci_build_apk.sh ${{ matrix.flutter_folder }}

  # Analyze, test and build for each web example.
  analyze-and-test-and-build-web:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        non_flutter_folder: ['packages/bloc/example', 'packages/bloc_test/example', 'examples/angular_counter', 'examples/github_search/common_github_search', 'examples/github_search/angular_github_search']
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.OS }}-flutter-cache-${{ env.flutter_version }}
          restore-keys: |
            ${{ runner.OS }}-flutter-cache-

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Analyze and test
        env:
          FLUTTER_DART_HOME: ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin
        run: |
          export PATH=$PATH:$FLUTTER_DART_HOME
          ./scripts/ci.sh ${{ matrix.non_flutter_folder }}

      - name: Build javascript
        env:
          FLUTTER_DART_HOME: ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin
        run: |
          export PATH=$PATH:$FLUTTER_DART_HOME
          ./scripts/ci_build_js.sh ${{ matrix.non_flutter_folder }}

