name: replay_bloc

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/replay_bloc.yaml"
      - "packages/replay_bloc/**"

  pull_request:
    paths:
      - ".github/workflows/replay_bloc.yaml"
      - "packages/replay_bloc/**"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/replay_bloc
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install Dependencies
        run: pub get
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Run Tests
        run: |
          pub global activate test_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          test_coverage
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: packages/replay_bloc/coverage/lcov.info
