name: replay_bloc

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/replay_bloc.yaml"
      - "packages/replay_bloc/**"

  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/replay_bloc.yaml"
      - "packages/replay_bloc/**"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/replay_bloc
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.10.0
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: pub get
      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .
      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib test
      - name: Run tests
        run: dart test --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
      - name: Check Code Coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: packages/replay_bloc/coverage/lcov.info
